### ISSUE TITLE
ssl error

### ISSUE THREAD

**Issue by efsfssf** [m3taphor/TinyVerse#9]
```
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\venv\Lib\site-packages\aiohttp\connector.py", line 992, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1113, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1146, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\main.py", line 15, in <module>
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\main.py", line 10, in main
    await process()
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\bot\utils\launcher.py", line 60, in process
    await run_tasks(accounts=accounts, used_session_names=used_session_names)
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\bot\utils\launcher.py", line 64, in run_tasks
    await build_check.check_base_url()
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\bot\utils\build_check.py", line 46, in check_base_url
    main_js_formats = await get_main_js_format(appUrl)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\bot\utils\build_check.py", line 21, in get_main_js_format
    async with aiohttp.request(url=base_url, method="GET", headers=headers) as response:
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\venv\Lib\site-packages\aiohttp\client.py", line 1243, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\venv\Lib\site-packages\aiohttp\client.py", line 578, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\venv\Lib\site-packages\aiohttp\connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\venv\Lib\site-packages\aiohttp\connector.py", line 911, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\venv\Lib\site-packages\aiohttp\connector.py", line 1235, in _create_direct_connection
    raise last_exc
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\venv\Lib\site-packages\aiohttp\connector.py", line 1204, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Documents\Games\TinyVerse-main\venv\Lib\site-packages\aiohttp\connector.py", line 994, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host app.tonverse.app:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')]

(venv) C:\Users\Administrator\Documents\Games\TinyVerse-main>python main.py

    ╔=▄╥▄▄▄▄╗╗ ╥▄   ▄▄╥ ╥╔▄▄▄▄╥╗ ╥▄▄▄▄▄╥  ,▄φφφφφ▄, ╥╔▄▄▄▄╥╗  ╔▄▄╥ - (TVerse)
       |█▓'    ▓▓   ║▓╫ ▓▓N      ▓▓И  ╞▓▌ |╫▓   ┣▓┦ ▓▓N       [▓▓▌
        ▓█|    ╬▓   ┣▓╫ ▓█L,╥=,  ╫╫L_ Æ╣] ╘╨▓║P_  ' ▓█L,╥=,   ╘║║╛
        ╫║     ┣▓▓__▓█╫ ║║Γ`""'  ▓▓Γ`┣▓   _     ▀█┳ ║║Γ`""'    ▓▓  - For education purpose
        █▓|     ╡╬▓▓╡╡  ▓▓_      ▓█   ╘█▌ ╫╪L   _█╫ ▓▓_        ▀▀  - Version: 2.0 (accounts.json edition)
        ╘"'      "╘╘    ╘╘╘""""' ╘""   ╘╘  """""""  ╘╘╘""""'   ╘╘  - By [G.Hub]: @m3taphor


-> Choose Option to continue (1/2):
    1. Run bot
    2. Create session


-> 1
TVerse 2.0 | 2024-12-16 20:19:12 | INFO     | 54 - Searched sessions: 1.
TVerse 2.0 | 2024-12-16 20:19:12 | SUCCESS  | 64 - Available accounts: 1.
TVerse 2.0 | 2024-12-16 20:19:12 | INFO     | 435 - StarsSpace | Starting in 8 seconds
TVerse 2.0 | 2024-12-16 20:19:21 | INFO     | 462 - StarsSpace | Trying to login
TVerse 2.0 | 2024-12-16 20:19:21 | ERROR    | 269 - StarsSpace | Unknown error when processing request: Cannot connect to host api.tonverse.app:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')]
TVerse 2.0 | 2024-12-16 20:19:22 | ERROR    | 467 - StarsSpace | Login Failed
TVerse 2.0 | 2024-12-16 20:19:22 | INFO     | 468 - StarsSpace | Sleep 57.8 min
TVerse 2.0 | 2024-12-16 20:19:29 | WARNING  | 17 - Bot stopped by user...
```

**Comment by m3taphor** [comment]
Hello, This error generally depend on the system server/network, Make sure to turn off all the HTTP Debugging software like Burp, Http Debugger before running the software software might be a reason for SSL issue. Additionally update your SSL & Modules of SSL for python/windows
